on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: build for linux x86_64 and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: generate buildsystem
        env:
          CXX: g++
        run: cmake -S . -B build -DSBASH64_BUDGET_ENABLE_WEB=1 -DCMAKE_BUILD_TYPE=Release
      - name: build backend
        run: cmake --build build --config Release --target sbash64-budget-web
      - name: build frontend
        run: bun build web/main.ts --outdir dist
      - name: zip files
        run: zip -j sbash64-budget-web-linux-x86_64.zip build/web/sbash64-budget-web web/index.html web/styles.css dist/main.js LICENSE NOTICE.txt
      - name: create GitHub release
        run: gh release create "${{ github.ref_name }}" *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
