on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-release:
    name: build and release for ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # https://github.community/t/how-to-get-just-the-tag-name/16241/7
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: generate buildsystem
        env:
          CXX: g++-10
        run: cmake -S . -B build -DSBASH64_BUDGET_ENABLE_WEB=1 -DCMAKE_BUILD_TYPE=Release
      - name: build app
        run: cmake --build build --config Release --target sbash64-budget-web
      - name: zip files
        run: zip sbash64-budget-web-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.zip build/web/sbash64-budget-web web/index.html web/main.js
      - name: create GitHub release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} -n "" -t ${{ steps.get_version.outputs.VERSION }} sbash64-budget-web-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}